[build]
  command = """
    pip install -r requirements.txt &&
    streamlit run streamlit_qr_generator.py
  """
  publish = "public"
  functions = "functions"

[build.environment]
  PYTHON_VERSION = "3.9"
  NODE_VERSION = "14"

[[redirects]]
  from = "/*"
  to = "/streamlit_qr_generator.py"
  status = 200

[dev]
  framework = "streamlit"
  targetPort = 8501

[functions]
  directory = "functions"
  node_bundler = "esbuild" 